### ISSUE TITLE
Springboot admin 监控含有server.servlet.context-path的应用

### ISSUE THREAD

**Issue by Longfei4AI** [Longfei4AI/Error-Logs#59]
```
spring:
  cloud:
    nacos:
      discovery:
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
```
